config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  get 'sessions/create'
  get 'users/new'
  get 'users/create'
  namespace :admin do
    get 'categories/index'
    get 'categories/new'
  end
  namespace :admin do
    get 'categories/index'
  end
  namespace :admin do
    get 'category/index'
  end
  get 'about/index'
  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :new, :create]
    resources :sales, only: [:index, :new]
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/category.rb
class Category < ApplicationRecord

  has_many :products

  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController

  def index
    @categories = Category.all
    pp @categories
  end

  def new
    @category = Category.new
    pp @category
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to [:admin, :categories], notice: 'Category created!'
    else
      render :new
    end
  
  end


  private

  def category_params
    params.require(:category).permit(
      :name
    )
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @products = @category.products.order(created_at: :desc)
  end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/index.html.erb
<h1 style="margin: 20px">Admin >> Categories</h1>

<div class="well">
<%= link_to '+ New category', new_admin_category_path, class: 'btn btn-info' %>
</div>


  <h3 style="margin: 10px">Category names</h3>

    <% @categories.each do |cat| %>

       <ul> 
        <li><%= cat.name%> created on: <%= cat.created_at%></li>
     
       </ul>

    <% end %> 
</table>

app/views/admin/categories/new.html.erb
<header class="page-header">
<h1>Admin &raquo; New category</h1>
</header>

<div class="well">
<%= link_to 'All Categories', [:admin, :categories], class: 'btn btn-info' %>
</div>   

  <%= form_for [:admin, @category] do |form| %>

    <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <strong>The following errors prevented saving:</strong>
            <ul>
              <% form.object.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        
    <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
    </div>
  <button type="Create new category" class="btn btn-primary" style="margin-top: 20px">Submit</button>
  <% end %>